#!/bin/sh -e

libdir="/home/marvin/wrk/projects/st/5g/nghttp2-1.33.0/lib"
if [ -d "$libdir/.libs" ]; then
    libdir="$libdir/.libs"
fi

export CGO_CFLAGS="-I/home/marvin/wrk/projects/st/5g/nghttp2-1.33.0/lib/includes -I/home/marvin/wrk/projects/st/5g/nghttp2-1.33.0/lib/includes"
export CGO_LDFLAGS="-L$libdir"
export LD_LIBRARY_PATH="$libdir"
export GODEBUG=cgocheck=0
"$@"
